# Generated by Django 4.1.3 on 2022-11-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moshin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firmasi', models.CharField(max_length=20)),
                ('nomi', models.CharField(max_length=20)),
                ('rangi', models.TextField()),
                ('yili', models.IntegerField(default=2000)),
            ],
        ),
    ]
