# Generated by Django 4.1.3 on 2022-11-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viloyati', models.TextField()),
                ('fakulteti', models.CharField(max_length=40)),
                ('kursi', models.IntegerField(default=1)),
                ('guruhi', models.CharField(max_length=20)),
            ],
        ),
    ]
