# Generated by Django 4.1.3 on 2022-11-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ins1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respublikasi', models.CharField(max_length=20)),
                ('viloyati', models.CharField(max_length=20)),
                ('fakultetlarisoni', models.IntegerField(default=2)),
                ('yonalishi', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ins2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kursi', models.IntegerField(default=1)),
                ('guruhi', models.CharField(max_length=10)),
                ('talabalarisoni', models.IntegerField(default=500)),
                ('talabasi', models.TextField()),
            ],
        ),
    ]
